### ISSUE TITLE
Sessions table is not created in mySQL upon commisioning

### ISSUE THREAD

**Issue by Xevrac** [aryxs3m/minecraft_portal#2]
When setting up instance, migrations complete but before getting to landing page stacktrace reports errors: Missing session table. 

If you make this table manually via a SQL client and proceed with the errors consecutively to make the rows you finally meet the login screen. 

When attempting to login with the in-game AuthMe credentials you receive a 419 Expired error. 

![image](https://user-images.githubusercontent.com/19704346/144691160-3b4d3710-ae6a-4c97-a97c-593bb9f0eca3.png)
![image](https://user-images.githubusercontent.com/19704346/144691176-90d67b93-5b1b-4b5e-87a3-a792ea160024.png)
![image](https://user-images.githubusercontent.com/19704346/144691242-22217072-23ac-4714-a877-700ab0a5dd9a.png)
![image](https://user-images.githubusercontent.com/19704346/144691182-9ebd9e0d-cf4d-40a6-966e-f784688f9bdf.png)
![image](https://user-images.githubusercontent.com/19704346/144691190-1b90435d-3780-4c3a-881a-d25133d419f9.png)

**Comment by Xevrac** [comment]
Minecraft version 1.18 on Paper MC
Laravel 8 
Using HeidiSQL 
AuthMe-5.6.0-beta2

**Comment by Xevrac** [comment]
Upon looking into the issue the 419 Page Expired has been resolved by setting in .env SESSION_DRIVER=database TO SESSION_DRIVER=file

**Comment by Xevrac** [comment]
Now facing issue with 
![image](https://user-images.githubusercontent.com/19704346/144692368-111e6c08-46a2-4bb1-ac58-18e359289230.png)
despite credentials inputted via game are matching what is in authme table

**Comment by Xevrac** [comment]
Seems like something isn't translating from AuthMe model in laravel to actual db entry for authme. Will look into further

**Comment by Xevrac** [comment]
To fix this credentials issue we needed to adjust the plugin settings from SHA stored passwords to BCRYPT which is far more favorable to the Laravel 8 framework (and standard)

Second issue was your MinecraftService.php was attempting to parse the QUERY_PORT from ENV as a string. 

To fix this LINE 15 needs: 
`            return MCPing::check(config('minecraft.server'), (int) config('minecraft.query_port'));`

The outcome of changing these vars results in the page loading as intended. 

Issue solved.

I'd suggest updating the install information on the README to advise of these minor changes.

**Comment by Xevrac** [comment]
I may be doing something wrong here: But for the /skin blade it also appears as though the players table and skins table is missing too.

**Comment by aryxs3m** [comment]
> stacktrace reports errors: Missing session table.
Database session doesn't supported, i recommend Redis, for caching too.

> To fix this credentials issue we needed to adjust the plugin settings from SHA stored passwords to BCRYPT
Ah yes, i forgot to add this in the README... Sorry.

> MinecraftService.php was attempting to parse the QUERY_PORT from ENV as a string
Just fixed it, thanks.

> players table and skins table is missing too
SkinRestorer plugin integration works like AuthMe, the SkinRestorer plugin create these tables itself. I forgot to add this in the README. Sorry again.

**Comment by Xevrac** [comment]
Thanks for responding :) 

And don't be sorry! We're all learning here! I think your platform is fantastic, iterations and improvements are only part of the fun ;)
